name = "oddlywiredco-site"
compatibility_date = "2026-01-01"

[triggers]
custom_domains = ["oddlywiredco.com"]

[[d1_databases]]
binding = "DB"
database_name = "oddlywiredco-newsletter"
database_id = "a55ef1cc-0551-42f6-843b-546547a4c48c"
